return {
  { import = 'plugins.guess-indent.guess-indent' },
  { import = 'plugins.gitsigns.gitsigns' },
  { import = 'plugins.fugitive.fugitive' },
  { import = 'plugins.neoscroll.neoscroll' },
  { import = 'plugins.typr.typr' },
  { import = 'plugins.vim-tmux-navigator.vim-tmux-navigator' },
  { import = 'plugins.which-key.which-key' },
  { import = 'plugins.telescope.telescope' },
  { import = 'plugins.lazydev.lazydev' },
  { import = 'plugins.nvim-lspconfig.nvim-lspconfig' },
  { import = 'plugins.conform.conform' },
  { import = 'plugins.undotree.undotree' },
  { import = 'plugins.oil.oil' },
  { import = 'plugins.blink-cmp.blink-cmp' },
  { import = 'plugins.nvim-cmp.nvim-cmp' },
  { import = 'plugins.obsidian.obsidian' },
  { import = 'plugins.markdown-preview.markdown-preview' },
  { import = 'plugins.opencode.opencode' },
  { import = 'plugins.onedark.onedark' },
  { import = 'plugins.mini.mini' },
  { import = 'plugins.nvim-treesitter.nvim-treesitter' },
  { import = 'plugins.indent-blankline.indent-blankline' },
  { import = 'plugins.render-markdown.render-markdown' },
}
